[project]
name = "customer-support-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fsspec>=2025.7.0",
    "huggingface-hub>=0.33.4",
    "loguru>=0.7.3",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
]
